### ISSUE TITLE
feat: Add prefix and suffix to the advanced_join fragment

### ISSUE THREAD

**Issue by sudojunior** [sudojunior/journey#21]
Currently the fragment covers each element it receives as nodes.
Each node is a predefined structure and only those properties are used in the fragment.

```yml
# advanced_join fragment schema
- !!node
  target: !!str | !!str[]
  char: !!str = ", "
  last: !!str = " and "
  connector: !!str = "; "
```

This also intended was to improve readability of the fragment to track how it constructs a string and to make room for formalized *sub fragment* injection. How this will happen is currently unknown, but the addition of `prefix` and `suffix` may require some reorganizing in the control flow and overall structure of what should be prioritized.

## Original idea

> *Remove `connector`, then replace with `prefix` and `suffix`.*

I now see that another approach should be used here, to ensure its deployment is clear to other contributors.
