### ISSUE TITLE
Ruby-less implementation of jekyll-octicons

### ISSUE THREAD

**Issue by sudojunior** [sudojunior/journey#3]
Considering that GitHub denies ruby scripts from external sources (except for [these](https://pages.github.com/versions/)), there might be an opportunity to implement them using standard HTML and CSS, or mirror what [fontawesome](https://fontawesome.com/) is able to do with their javascript extension and reimplement that for a GitHub Jekyll deployment.

¯\\\_(ツ)\_/¯

**Comment by sudojunior** [comment]
First attempt at using jekyll only with external ref on svg
```
{% assign color = include.color | default: 'black' %}
{% assign icon = include.icon %}
{% assign size = include.size | default: 16 %}
<svg class="octicon octicon-{{ color }}" viewBox="0 0 {{ size }} {{ size }}">
  <style>
    svg.octicon.octicon-{{ size }} {
      width: {{ size }}px;
      height: {{ size }}px;
    }

    svg.octicon.octicon-{{ color }} {
      fill: {{ color }};
    }
  </style>
  <use width="{{ size }}" height="{{ size }}" src="https://raw.githubusercontent.com/primer/octicons/master/icons/{{ include.icon }}-{{ size }}.svg"></use>
</svg>
```

**Comment by sudojunior** [comment]
Second attempt is using sass (.scss) but the file didn't render as a .css file so it couldn't be used.
```scss
$icons: "alert", "archive";

$sizes: 16, 24;

@each $size in $sizes {
  @each $icon in $icons {
    .octicons .octicons-#{$icon}-#{$size} {
      width: #{$size}px;
      height: #{$size}px;
      content: url(https://github.com/primer/octicons/blob/master/icons/#{$icon}-#{$size}.svg);
    }
  }
}
```

**Comment by sudojunior** [comment]
The third attempt is using standard CSS in the background field, it works until you need to give it a color...
```css


span.octicon.octicon-alert-16 {
  width: 16px;
  height: 16px;
  background-image: url(https://raw.githubusercontent.com/primer/octicons/master/icons/alert-16.svg);
}

span.octicon.octicon-white {
  background-color: white;
}
```
*This can be looped using some iteration code or data files in the main environment*
```yml
# sample of _data/octicons.yml
icons:
  [
    alert, archive, arrow-both, arrow-down, arrow-left, arrow-right
  ]

sizes:
  - 16
  - 24
```
